#!/bin/bash
rm -rf newboot.img
if [[ "$1" == *"-h"* ]]; then
mk-bootimg --kernel *boot.img-kernel --ramdisk *boot.img-ramdisk.gz --cmdline "androidboot.hardware=qcom usb_id_pin_rework=true no_console_suspend=true zcache" --base 0x40400000 --pagesize 2048 --output newboot.img --ramdisk_offset 0x01400000
elif [[ "$1" == *"-d"* ]]; then
mk-bootimg --kernel *boot.img-kernel --ramdisk *boot.img-ramdisk.gz --cmdline "no_console_suspend=1 androidboot.selinux=permissive" --base 0x48000000 --output newboot.img --pagesize 2048
else
echo You must specify the device
fi
